#!/bin/bash

# Load environment variables from .env file if it exists
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Check if required environment variables are set
if [ -z "$DB_USERNAME" ] || [ -z "$DB_PASSWORD" ]; then
    echo "Error: DB_USERNAME and DB_PASSWORD must be set"
    echo "Please create a .env file with your credentials or export them as environment variables"
    exit 1
fi

# Optional: Set defaults for host, port, and SID if not provided
DB_HOST="${DB_HOST:-oracle.scs.ryerson.ca}"
DB_PORT="${DB_PORT:-1521}"
DB_SID="${DB_SID:-orcl}"

# Construct connection string
CONNECTION_STRING="${DB_USERNAME}/${DB_PASSWORD}@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=${DB_HOST})(Port=${DB_PORT}))(CONNECT_DATA=(SID=${DB_SID})))"

sqlplus "$CONNECTION_STRING" <<EOF

-- Insert hospital personnel first (parent for orders/assignments)
INSERT INTO HOSPITAL_PERSONNEL (PERSONNEL_ID, PERSONNEL_NAME, DEPARTMENT, PERSONNEL_ROLE, ACCESS_LEVEL) VALUES (1, 'Dr. Sarah Johnson', 'Cardiology', 'Doctor', 5);
INSERT INTO HOSPITAL_PERSONNEL (PERSONNEL_ID, PERSONNEL_NAME, DEPARTMENT, PERSONNEL_ROLE, ACCESS_LEVEL) VALUES (2, 'Nurse Mark Williams', 'Emergency', 'Nurse', 3);
INSERT INTO HOSPITAL_PERSONNEL (PERSONNEL_ID, PERSONNEL_NAME, DEPARTMENT, PERSONNEL_ROLE, ACCESS_LEVEL) VALUES (3, 'Dr. Emily Chen', 'Pediatrics', 'Doctor', 5);

-- Insert patients
INSERT INTO PATIENT_LIST (PATIENT_ID, PATIENT_NAME, ADMITTED_TIME, DIAGNOSIS, DISCHARGE_TIME) VALUES (101, 'John Smith', TO_DATE('2025-09-20', 'YYYY-MM-DD'), 'Acute Myocardial Infarction', NULL);
INSERT INTO PATIENT_LIST (PATIENT_ID, PATIENT_NAME, ADMITTED_TIME, DIAGNOSIS, DISCHARGE_TIME) VALUES (102, 'Maria Garcia', TO_DATE('2025-09-22', 'YYYY-MM-DD'), 'Pneumonia', NULL);
INSERT INTO PATIENT_LIST (PATIENT_ID, PATIENT_NAME, ADMITTED_TIME, DIAGNOSIS, DISCHARGE_TIME) VALUES (103, 'Robert Lee', TO_DATE('2025-09-15', 'YYYY-MM-DD'), 'Appendicitis', TO_DATE('2025-09-18', 'YYYY-MM-DD'));

-- Assign personnel to patients
INSERT INTO HOSP_PERSONNEL_PAT_ASSIGN (PATIENT_ID, PERSONNEL_ID) VALUES (101, 1);
INSERT INTO HOSP_PERSONNEL_PAT_ASSIGN (PATIENT_ID, PERSONNEL_ID) VALUES (102, 2);
INSERT INTO HOSP_PERSONNEL_PAT_ASSIGN (PATIENT_ID, PERSONNEL_ID) VALUES (102, 3);

-- Insert pharmacy inventory (parent for hospital orders)
INSERT INTO PHARM_MED_INVENTORY 
    (MEDICINE_ID, DRUG_NAME, DOSAGE, DRUG_DESCRIPTION, COMPANY, QUANTITY, DRUG_TYPE, ACCESS_LEVEL, EXPIRY_DATE, DRUG_COST)
VALUES 
    (1001, 'Aspirin', '100mg', 'Pain reliever and anti-inflammatory', 'PharmaCorp', 5000, 'Tablet', 1, TO_DATE('2026-12-31', 'YYYY-MM-DD'), 0.50);

INSERT INTO PHARM_MED_INVENTORY 
    (MEDICINE_ID, DRUG_NAME, DOSAGE, DRUG_DESCRIPTION, COMPANY, QUANTITY, DRUG_TYPE, ACCESS_LEVEL, EXPIRY_DATE, DRUG_COST)
VALUES 
    (1002, 'Morphine Sulfate', '10mg/mL', 'Opioid analgesic for severe pain', 'MedSupply Inc', 200, 'Injectable', 5, TO_DATE('2025-11-30', 'YYYY-MM-DD'), 25.00);

INSERT INTO PHARM_MED_INVENTORY 
    (MEDICINE_ID, DRUG_NAME, DOSAGE, DRUG_DESCRIPTION, COMPANY, QUANTITY, DRUG_TYPE, ACCESS_LEVEL, EXPIRY_DATE, DRUG_COST)
VALUES 
    (1003, 'Amoxicillin', '500mg', 'Antibiotic for bacterial infections', 'GlobalMed', 3000, 'Capsule', 2, TO_DATE('2026-06-30', 'YYYY-MM-DD'), 1.25);

INSERT INTO PHARM_MED_INVENTORY
    (MEDICINE_ID, DRUG_NAME, DOSAGE, DRUG_DESCRIPTION, COMPANY, QUANTITY, DRUG_TYPE, ACCESS_LEVEL, EXPIRY_DATE, DRUG_COST)
VALUES 
    (1004, 'skill issue pills', '200mg', 'For Skill Issues', 'SKINC', 5000, 'Tablet', 1, TO_DATE('2026-06-30', 'YYYY-MM-DD'), 0.01);



-- Insert hospital medicine inventory (child of PHARM_MED_INVENTORY)
INSERT INTO HOSP_MED_INVENTORY (MEDICINE_ID, QUANTITY) VALUES (1001, 500);
INSERT INTO HOSP_MED_INVENTORY (MEDICINE_ID, QUANTITY) VALUES (1002, 50);
INSERT INTO HOSP_MED_INVENTORY (MEDICINE_ID, QUANTITY) VALUES (1003, 300);

-- Insert pharmacy supply inventory (parent for hospital supply orders)
INSERT INTO PHARM_SUPPLY_INVENTORY (SUPPLY_ID, SUPPLY_NAME, SUPPLY_DESCRIPTION, QUANTITY, SUPPLY_COST, COMPANY)
VALUES (2001, 'Surgical Gloves', 'Latex-free sterile gloves size M', 10000, 0.35, 'MedicalSupplies Co');
INSERT INTO PHARM_SUPPLY_INVENTORY (SUPPLY_ID, SUPPLY_NAME, SUPPLY_DESCRIPTION, QUANTITY, SUPPLY_COST, COMPANY)
VALUES (2002, 'IV Catheter 20G', '20 gauge intravenous catheter', 5000, 2.50, 'CareSupply Inc');
INSERT INTO PHARM_SUPPLY_INVENTORY (SUPPLY_ID, SUPPLY_NAME, SUPPLY_DESCRIPTION, QUANTITY, SUPPLY_COST, COMPANY)
VALUES (2003, 'Syringes 10mL', 'Sterile disposable syringes', 8000, 0.75, 'MedicalSupplies Co');

-- Insert hospital supply inventory (child of PHARM_SUPPLY_INVENTORY)
INSERT INTO HOSP_SUPPLY_INVENTORY (SUPPLY_ID, QUANTITY) VALUES (2001, 1000);
INSERT INTO HOSP_SUPPLY_INVENTORY (SUPPLY_ID, QUANTITY) VALUES (2002, 200);
INSERT INTO HOSP_SUPPLY_INVENTORY (SUPPLY_ID, QUANTITY) VALUES (2003, 500);

-- Insert patient medicine orders (child of HOSP_MED_INVENTORY & HOSPITAL_PERSONNEL)
INSERT INTO PATIENT_MED_ORDER (ORDER_ID, PERSONNEL_ID, PATIENT_ID, MEDICINE_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (3001, 1, 101, 1001, 30, TO_DATE('2025-09-20', 'YYYY-MM-DD'), TO_DATE('2025-09-20', 'YYYY-MM-DD'));
INSERT INTO PATIENT_MED_ORDER (ORDER_ID, PERSONNEL_ID, PATIENT_ID, MEDICINE_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (3002, 2, 102, 1003, 20, TO_DATE('2025-09-22', 'YYYY-MM-DD'), TO_DATE('2025-09-22', 'YYYY-MM-DD'));
INSERT INTO PATIENT_MED_ORDER (ORDER_ID, PERSONNEL_ID, PATIENT_ID, MEDICINE_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (3003, 1, 101, 1002, 5, TO_DATE('2025-09-21', 'YYYY-MM-DD'), NULL);

-- Insert hospital medicine orders (child of HOSP_MED_INVENTORY & HOSPITAL_PERSONNEL)
INSERT INTO HOSP_MED_ORDER (ORDER_ID, PERSONNEL_ID, MEDICINE_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (4001, 2, 1001, 1000, TO_DATE('2025-09-18', 'YYYY-MM-DD'), TO_DATE('2025-09-19', 'YYYY-MM-DD'));
INSERT INTO HOSP_MED_ORDER (ORDER_ID, PERSONNEL_ID, MEDICINE_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (4002, 1, 1002, 100, TO_DATE('2025-09-20', 'YYYY-MM-DD'), NULL);
INSERT INTO HOSP_MED_ORDER (ORDER_ID, PERSONNEL_ID, MEDICINE_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (4003, 3, 1003, 500, TO_DATE('2025-09-23', 'YYYY-MM-DD'), TO_DATE('2025-09-24', 'YYYY-MM-DD'));
INSERT INTO HOSP_MED_ORDER (ORDER_ID, PERSONNEL_ID, MEDICINE_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES(4004, 3, 1001, 100, TO_DATE('2025-09-23', 'YYYY-MM-DD'),  NULL);


-- Insert hospital supply orders (child of HOSP_SUPPLY_INVENTORY & HOSPITAL_PERSONNEL)
INSERT INTO HOSP_SUPPLY_ORDER (ORDER_ID, PERSONNEL_ID, SUPPLY_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (5001, 2, 2001, 2000, TO_DATE('2025-09-19', 'YYYY-MM-DD'), TO_DATE('2025-09-20', 'YYYY-MM-DD'));
INSERT INTO HOSP_SUPPLY_ORDER (ORDER_ID, PERSONNEL_ID, SUPPLY_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (5002, 1, 2002, 500, TO_DATE('2025-09-21', 'YYYY-MM-DD'), NULL);
INSERT INTO HOSP_SUPPLY_ORDER (ORDER_ID, PERSONNEL_ID, SUPPLY_ID, QUANTITY, ORDER_DATE, RECEIVED_DATE)
VALUES (5003, 3, 2003, 1000, TO_DATE('2025-09-22', 'YYYY-MM-DD'), TO_DATE('2025-09-23', 'YYYY-MM-DD'));

COMMIT;


exit;
EOF